Algoritmo "calculo_de_idade"

Var
anodenascimento:real
mesdenascimento:real
diadenascimento:real
idade:real
anoatual:real
mesatual:real
diaatual :real
Inicio
Escreva("Insira o ano em que nasceu:")
leia(anodenascimento)
Escreva("Insira o mês em que nasceu:")
leia(mesdenascimento)
Escreva("Insira o dia em que nasceu:")
leia(diadenascimento)
Escreva("Insira o ano atual:")
leia(anoatual)
Escreva("Insira o mês atual:")
leia(mesatual)
Escreva("Insira o dia atual:")
leia(diaatual)
idade <-anoatual- anodenascimento
Escreva("Você tem :",idade)
Fimalgoritmo