Algoritmo "semnome"

Var
N1, N2, Resultado:real
Inicio
escreva("Entrada com N1:")
leia(N1)
escreva("Entrada com N2:")
leia(N2)
Resultado<-(N1+N2)
escreva("O resultado da soma:",Resultado)


escreva("Entrada com N1:")
leia(N1)
escreva("Entrada com N2:")
leia(N2)
Resultado<-(N1-N2)
escreva("O resultado da subtração:",Resultado)


escreva("Entrada com N1:")
leia(N1)
escreva("Entrada com N2:")
leia(N2)
Resultado<-(N1/N2)
escreva("O resultado da divisão:",Resultado)


escreva("Entrada com N1:")
leia(N1)
escreva("Entrada com N2:")
leia(N2)
Resultado<-(N1*N2)
escreva("O resultado da multiplicação:",Resultado)
fimalgoritmo
