Algoritmo "par_impar"
//Autor: Wilcar Alexandre
//Sala:15
//Curso: Informática de gestão
Var
N1:inteiro
N2:inteiro
N3:inteiro
N4:inteiro
N5:inteiro
Inicio
Escreva("Insira o primeiro número: ")
leia(N1)
se (N1 mod 2) = 0 entao
Escreva("O número é par")
senao
Escreva("O número é impar")
fimse

Escreva("Insira o segundo número: ")
leia(N2)
se N2 mod 2= 0 entao
Escreva("O número é par")
senao N2 impar
Escreva("O número é impar")
fimse

Escreva("Insira o terceiro número: ")
leia(N3)
se N3 mod 2= 0 entao
Escreva("O número é par")
senao N3 impar
escreva("O número é impar")
fimse

Escreva("Insira o quarto número: ")
leia(N4)
se N4 mod 2= 0 entao
Escreva("O número é par")
senao N4 impar
Escreva("O número é impar")
fimse

Escreva("Insira o quinto número: ")
leia(N5)
se N5 mod 2= 0 entao
Escreva("O número é par")
senao N5 impar
Escreva("O número é impar")
fimse
fimalgoritmo